// Code generated by `go run ./cmd/stdgen` from hana/std — DO NOT EDIT.
// Edit the name tables in hana/std and regenerate.

export const stdModules = [
  {
    id: "math",
    name: "数学",
    functions: [
      { id: "math.ceil", name: "切り上げ" },
      { id: "math.floor", name: "切り捨て" },
    ],
  },
] as const;
