// Code generated by `go run ./cmd/stdgen` from hana/std — DO NOT EDIT.
// Edit the name tables in hana/std and regenerate.

export interface StdModule {
  id: string;
  name: string;
  nativeOnly?: boolean;
  functions: readonly { id: string; name: string }[];
}

export const stdModules: readonly StdModule[] = [
  {
    id: "math",
    name: "数学",
    functions: [
      { id: "math.ceil", name: "切り上げ" },
      { id: "math.floor", name: "切り捨て" },
      { id: "math.sqrt", name: "平方根" },
      { id: "math.pow", name: "べき乗" },
      { id: "math.abs", name: "絶対値" },
      { id: "math.round", name: "四捨五入" },
      { id: "math.sin", name: "サイン" },
      { id: "math.cos", name: "コサイン" },
      { id: "math.tan", name: "タンジェント" },
      { id: "math.log", name: "対数" },
      { id: "math.pi", name: "円周率" },
      { id: "math.gcd", name: "最大公約数" },
      { id: "math.factorial", name: "階乗" },
    ],
  },
  {
    id: "json",
    name: "JSON",
    functions: [
      { id: "json.parse", name: "パース" },
      { id: "json.stringify", name: "文字列化" },
    ],
  },
  {
    id: "random",
    name: "乱数",
    functions: [
      { id: "random.float", name: "実数" },
      { id: "random.int", name: "整数" },
      { id: "random.choice", name: "選ぶ" },
      { id: "random.shuffle", name: "シャッフル" },
      { id: "random.uuid", name: "UUID" },
    ],
  },
  {
    id: "datetime",
    name: "日時",
    functions: [
      { id: "datetime.now", name: "今" },
      { id: "datetime.format", name: "書式" },
      { id: "datetime.parse", name: "読み取り" },
      { id: "datetime.weekday", name: "曜日" },
      { id: "datetime.sleep", name: "待つ" },
    ],
  },
  {
    id: "stats",
    name: "統計",
    functions: [
      { id: "stats.sum", name: "合計" },
      { id: "stats.min", name: "最小値" },
      { id: "stats.max", name: "最大値" },
      { id: "stats.mean", name: "平均" },
      { id: "stats.median", name: "中央値" },
      { id: "stats.stdev", name: "標準偏差" },
    ],
  },
  {
    id: "text",
    name: "テキスト",
    functions: [
      { id: "text.upper", name: "大文字" },
      { id: "text.lower", name: "小文字" },
      { id: "text.strip", name: "トリム" },
      { id: "text.padleft", name: "左埋め" },
      { id: "text.padright", name: "右埋め" },
      { id: "text.repeat", name: "繰り返し" },
      { id: "text.reverse", name: "逆さ" },
      { id: "text.startswith", name: "始まるか" },
      { id: "text.endswith", name: "終わるか" },
      { id: "text.join", name: "連結" },
      { id: "text.count", name: "数える" },
      { id: "text.find", name: "位置" },
    ],
  },
  {
    id: "list",
    name: "リスト",
    functions: [
      { id: "list.sort", name: "並べ替え" },
      { id: "list.reverse", name: "反転" },
      { id: "list.unique", name: "重複除去" },
      { id: "list.range", name: "範囲" },
      { id: "list.flatten", name: "平坦化" },
      { id: "list.chunk", name: "小分け" },
      { id: "list.zip", name: "ペア" },
      { id: "list.map", name: "変換" },
      { id: "list.filter", name: "絞り込み" },
      { id: "list.reduce", name: "畳み込み" },
      { id: "list.find", name: "探す" },
      { id: "list.any", name: "どれか" },
      { id: "list.all", name: "すべて" },
      { id: "list.sortby", name: "基準並べ替え" },
    ],
  },
  {
    id: "encoding",
    name: "エンコード",
    functions: [
      { id: "encoding.base64encode", name: "Base64エンコード" },
      { id: "encoding.base64decode", name: "Base64デコード" },
      { id: "encoding.urlencode", name: "URLエンコード" },
      { id: "encoding.urldecode", name: "URLデコード" },
    ],
  },
  {
    id: "hash",
    name: "ハッシュ",
    functions: [
      { id: "hash.sha256", name: "SHA256" },
    ],
  },
  {
    id: "file",
    name: "ファイル",
    nativeOnly: true,
    functions: [
      { id: "file.read", name: "読む" },
      { id: "file.lines", name: "行で読む" },
      { id: "file.write", name: "書く" },
      { id: "file.append", name: "追記" },
      { id: "file.exists", name: "あるか" },
      { id: "file.isdir", name: "フォルダか" },
      { id: "file.delete", name: "削除" },
      { id: "file.list", name: "一覧" },
      { id: "file.mkdir", name: "フォルダ作成" },
      { id: "file.move", name: "移動" },
    ],
  },
  {
    id: "path",
    name: "パス",
    functions: [
      { id: "path.join", name: "結合" },
      { id: "path.dirname", name: "フォルダ名" },
      { id: "path.basename", name: "ファイル名" },
      { id: "path.ext", name: "拡張子" },
      { id: "path.stem", name: "拡張子なし名" },
      { id: "path.withext", name: "拡張子変更" },
      { id: "path.normalize", name: "正規化" },
      { id: "path.isabs", name: "絶対パスか" },
      { id: "path.parts", name: "構成要素" },
    ],
  },
  {
    id: "regex",
    name: "正規表現",
    functions: [
      { id: "regex.test", name: "検査" },
      { id: "regex.find", name: "検索" },
      { id: "regex.groups", name: "グループ" },
      { id: "regex.findall", name: "全検索" },
      { id: "regex.replace", name: "置換" },
      { id: "regex.split", name: "分割" },
    ],
  },
];
